before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy

env:
  - GITHUB_USER=tbckr
  - GITHUB_REPO=tbckr/sgpt
  - IMAGE_NAME=ghcr.io/tbckr/sgpt
  - SCOOP_BUCKET=scoop-bucket
  - HOMEBREW_TAP=homebrew-tap

gomod:
  proxy: true
  env:
    - GOPROXY=https://proxy.golang.org,direct
    - GOSUMDB=sum.golang.org

builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/sgpt
    binary: sgpt
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - "386"
      - "amd64"
      - "arm"
      - "arm64"
    goarm:
      - 7
    ignore:
      - goos: windows
        goarch: arm
    ldflags:
      - -X 'github.com/tbckr/sgpt/internal/buildinfo.version={{.Version}}'
      - -X 'github.com/tbckr/sgpt/internal/buildinfo.commit={{.Commit}}'
      - -X 'github.com/tbckr/sgpt/internal/buildinfo.commitDate={{.CommitDate}}'

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
    - goos: windows
      format: zip

sboms:
  - artifacts: archive

dockers:
  -
    id: "linux-amd64"
    goos: linux
    goarch: amd64
    use: buildx
    dockerfile: "Dockerfile.goreleaser"
    image_templates:
    - "{{.Env.IMAGE_NAME}}:latest-amd64"
    - "{{.Env.IMAGE_NAME}}:{{ .Major }}-amd64"
    - "{{.Env.IMAGE_NAME}}:{{ .Major }}.{{.Minor}}-amd64"
    - "{{.Env.IMAGE_NAME}}:{{ .Major }}.{{.Minor}}.{{.Patch}}-amd64"
    # Template of the docker build flags.
    build_flag_templates:
    - "--pull"
    - "--platform=linux/amd64"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--label=org.opencontainers.image.description={{ .ProjectName }}"
    - "--label=org.opencontainers.image.url=https://github.com/tbckr/{{ .ProjectName }}"
    - "--label=org.opencontainers.image.source=https://github.com/tbckr/{{ .ProjectName }}"
    - "--label=org.opencontainers.image.licenses=MIT"
  -
    id: "linux-arm64"
    goos: linux
    goarch: arm64
    use: buildx
    dockerfile: "Dockerfile.goreleaser"
    image_templates:
    - "{{.Env.IMAGE_NAME}}:latest-arm64"
    - "{{.Env.IMAGE_NAME}}:{{ .Major }}-arm64"
    - "{{.Env.IMAGE_NAME}}:{{ .Major }}.{{.Minor}}-arm64"
    - "{{.Env.IMAGE_NAME}}:{{ .Major }}.{{.Minor}}.{{.Patch}}-arm64"
    # Template of the docker build flags.
    build_flag_templates:
    - "--pull"
    - "--platform=linux/arm64"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--label=org.opencontainers.image.description={{ .ProjectName }}"
    - "--label=org.opencontainers.image.url=https://github.com/tbckr/{{ .ProjectName }}"
    - "--label=org.opencontainers.image.source=https://github.com/tbckr/{{ .ProjectName }}"
    - "--label=org.opencontainers.image.licenses=MIT"
  -
    id: "linux-armv7"
    goos: linux
    goarch: arm
    goarm: 7
    use: buildx
    dockerfile: "Dockerfile.goreleaser"
    image_templates:
    - "{{.Env.IMAGE_NAME}}:latest-armv7"
    - "{{.Env.IMAGE_NAME}}:{{ .Major }}-armv7"
    - "{{.Env.IMAGE_NAME}}:{{ .Major }}.{{.Minor}}-armv7"
    - "{{.Env.IMAGE_NAME}}:{{ .Major }}.{{.Minor}}.{{.Patch}}-armv7"
    # Template of the docker build flags.
    build_flag_templates:
    - "--pull"
    - "--platform=linux/arm64"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--label=org.opencontainers.image.description={{ .ProjectName }}"
    - "--label=org.opencontainers.image.url=https://github.com/tbckr/{{ .ProjectName }}"
    - "--label=org.opencontainers.image.source=https://github.com/tbckr/{{ .ProjectName }}"
    - "--label=org.opencontainers.image.licenses=MIT"
  -
    id: "linux-386"
    goos: linux
    goarch: 386
    use: buildx
    dockerfile: "Dockerfile.goreleaser"
    image_templates:
    - "{{.Env.IMAGE_NAME}}:latest-386"
    - "{{.Env.IMAGE_NAME}}:{{ .Major }}-386"
    - "{{.Env.IMAGE_NAME}}:{{ .Major }}.{{.Minor}}-386"
    - "{{.Env.IMAGE_NAME}}:{{ .Major }}.{{.Minor}}.{{.Patch}}-386"
    # Template of the docker build flags.
    build_flag_templates:
    - "--pull"
    - "--platform=linux/arm64"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--label=org.opencontainers.image.description={{ .ProjectName }}"
    - "--label=org.opencontainers.image.url=https://github.com/tbckr/{{ .ProjectName }}"
    - "--label=org.opencontainers.image.source=https://github.com/tbckr/{{ .ProjectName }}"
    - "--label=org.opencontainers.image.licenses=MIT"

docker_manifests:
- name_template: "{{.Env.IMAGE_NAME}}:{{ .Major }}.{{.Minor}}.{{.Patch}}"
  image_templates:
  - "{{.Env.IMAGE_NAME}}:{{ .Major }}.{{.Minor}}.{{.Patch}}-amd64"
  - "{{.Env.IMAGE_NAME}}:{{ .Major }}.{{.Minor}}.{{.Patch}}-arm64"
  - "{{.Env.IMAGE_NAME}}:{{ .Major }}.{{.Minor}}.{{.Patch}}-armv7"
  - "{{.Env.IMAGE_NAME}}:{{ .Major }}.{{.Minor}}.{{.Patch}}-386"
- name_template: "{{.Env.IMAGE_NAME}}:{{ .Major }}.{{.Minor}}"
  image_templates:
  - "{{.Env.IMAGE_NAME}}:{{ .Major }}.{{.Minor}}-amd64"
  - "{{.Env.IMAGE_NAME}}:{{ .Major }}.{{.Minor}}-arm64"
  - "{{.Env.IMAGE_NAME}}:{{ .Major }}.{{.Minor}}-armv7"
  - "{{.Env.IMAGE_NAME}}:{{ .Major }}.{{.Minor}}-386"
- name_template: "{{.Env.IMAGE_NAME}}:{{ .Major }}"
  image_templates:
  - "{{.Env.IMAGE_NAME}}:{{ .Major }}-amd64"
  - "{{.Env.IMAGE_NAME}}:{{ .Major }}-arm64"
  - "{{.Env.IMAGE_NAME}}:{{ .Major }}-armv7"
  - "{{.Env.IMAGE_NAME}}:{{ .Major }}-386"
- name_template: "{{.Env.IMAGE_NAME}}:latest"
  image_templates:
  - "{{.Env.IMAGE_NAME}}:latest-amd64"
  - "{{.Env.IMAGE_NAME}}:latest-arm64"
  - "{{.Env.IMAGE_NAME}}:latest-armv7"
  - "{{.Env.IMAGE_NAME}}:latest-386"

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore'
      - 'merge conflict'
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - title: Dependency updates
      regexp: '^.*?(feat|fix)\(deps\)!?:.+$'
      order: 300
    - title: 'New Features'
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 100
    - title: 'Bug fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 200
    - title: 'Documentation updates'
      regexp: ^.*?doc(\([[:word:]]+\))??!?:.+$
      order: 400
    - title: 'Build process updates'
      regexp: ^.*?build(\([[:word:]]+\))??!?:.+$
      order: 400
    - title: Other work
      order: 9999

scoop:
  bucket:
    owner: "{{ .Env.GITHUB_USER }}"
    name: "{{ .Env.SCOOP_BUCKET }}"
    token: "{{ .Env.SCOOP_TAP_GITHUB_TOKEN }}"
  commit_author:
    name: "goreleaserbot"
    email: "11543666+tbckr@users.noreply.github.com"
  commit_msg_template: "feat: Scoop update for {{ .ProjectName }} version {{ .Tag }}"
  description: "SGPT is a command-line tool that provides a convenient way to interact with OpenAI models, enabling users to run queries, generate shell commands, produce code, and create images from text directly from the terminal."
  license: MIT

brews:
  - tap:
      owner: "{{ .Env.GITHUB_USER }}"
      name: "{{ .Env.HOMEBREW_TAP }}"
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_author:
      name: "goreleaserbot"
      email: "11543666+tbckr@users.noreply.github.com"
    commit_msg_template: "feat: Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    folder: Formula
    description: "SGPT is a command-line tool that provides a convenient way to interact with OpenAI models, enabling users to run queries, generate shell commands, produce code, and create images from text directly from the terminal."
    license: MIT
    dependencies:
    - name: go
      type: optional

# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
