FROM --platform=$BUILDPLATFORM cgr.dev/chainguard/static:latest@sha256:da9822ad6f973e40e24e75133b08ae874900766873ecd03e58f7f630ccea898c

ENV HOME /home/nonroot
VOLUME /home/nonroot

COPY sgpt /sgpt
ENTRYPOINT ["/sgpt"]