FROM --platform=$BUILDPLATFORM cgr.dev/chainguard/static:latest@sha256:d6621cc6a8d7d6504c701dce729b020b74e696af1715335b3390dc194f2195c0

ENV HOME /home/nonroot
VOLUME /home/nonroot

COPY sgpt /sgpt
ENTRYPOINT ["/sgpt"]