ARG BUILDPLATFORM=linux/amd64
ARG BASE_IMAGE_VERSION=cgr.dev/chainguard/static:latest@sha256:77d8b8925dc27970ec2f48243f44c7a260d52c49cd778288e4ee97566e0cb75b
FROM --platform=$BUILDPLATFORM ${BASE_IMAGE_VERSION}
ENV HOME /home/nonroot
VOLUME /home/nonroot
COPY sgpt /sgpt
ENTRYPOINT ["/sgpt"]