# Copyright (c) 2023 Tim <tbckr>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
# SPDX-License-Identifier: MIT

name: go-licenses

on:
  # run action when a change lands in the main branch which updates go.mod or
  # our license template file. Also allow manual triggering.
  push:
    branches:
      - main
    paths:
      - go.mod
      - .github/licenses.tmpl
      - .github/workflows/go-licenses.yml
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-$${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  update-licenses:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - name: Install go-licenses
        run: |
          go install github.com/google/go-licenses@v1.2.2-0.20220825154955-5eedde1c6584
      - name: Run go-licenses
        env:
          # include all build tags to include platform-specific dependencies
          GOFLAGS: "-tags=darwin,linux,windows"
        run: |
          [ -d licenses ] || mkdir -p licenses
          go-licenses report github.com/tbckr/sgpt/cmd/sgpt > licenses/licenses.md --template .github/licenses.tmpl
          git config --global user.name 'Tim'
          git config --global user.email '11543666+tbckr@users.noreply.github.com'
          git commit -am "chore: update licenses/licenses.md file"
          git push
  check-license-header:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - name: Install go-licenses
        run: |
          go install github.com/google/addlicense@latest
      - name: Run addlicense check
        run: |
          ./scripts/check-license-header.sh
